In [1]:
import numpy as np

### Problema 1 (a)

In [2]:
x = np.array([
    -100, -100, -100, 400
])

y = np.array([
    -200, -50, -50, 400
])

In [3]:
x + y

array([-300, -150, -150,  800])

In [4]:
np.dot(x, y) #Seriam ortogonais se np.dot(x, y) = 0, logo, x e y não são ortogonais.

190000

In [5]:
print(f'A norma de x é {np.linalg.norm(x)} e a norma de y é {np.linalg.norm(y)}')

A norma de x é 435.88989435406734 e a norma de y é 452.76925690687085


In [6]:
print(f'A distância euclideana entre x e y é {np.linalg.norm(x - y)}. Distância Manhattan é {np.linalg.norm(x-y, ord=1)}')

A distância euclideana entre x e y é 122.47448713915891. Distância Manhattan é 200.0


In [7]:
A = np.vstack((x, y)).T

print(A)

[[-100 -200]
 [-100  -50]
 [-100  -50]
 [ 400  400]]


In [8]:
np.linalg.matrix_rank(A) #Posto coluna = 2 = #colunas LI. Segue que x e y são vetores LI.

2

### Problema 1 (b)

In [9]:
A = np.array([
    [0.9, 0.2],
    [0.1, 0.8]
])

In [10]:
A.T

array([[0.9, 0.1],
       [0.2, 0.8]])

In [11]:
A.T @ A #Simétrica visualmente; você consegue pensar num teste formal de simetria no numpy?

array([[0.82, 0.26],
       [0.26, 0.68]])

In [12]:
np.linalg.inv(A) #Invertível implica posto completo. Próximo subitem é redundante.

array([[ 1.14285714, -0.28571429],
       [-0.14285714,  1.28571429]])

In [13]:
np.linalg.matrix_rank(A) #Posto completo.

2

In [14]:
np.trace(A)

1.7000000000000002

In [15]:
np.linalg.det(A)

0.7000000000000001

In [16]:
spectre, S = np.linalg.eig(A)

print(f'O espectro da matriz A é o vetor: {spectre}')

O espectro da matriz A é o vetor: [1.  0.7]


### Problema 1 (c)

In [17]:
A = np.array([
    [-0.9, 0.2],
    [0.1, 0.8]
])

In [18]:
for matrix in [A]:
    
    if (matrix > 1).any() or sum(A[:, 0]) + sum(A[:, 1]) > 2:
        
        print('Sua matriz não é de Markov!')
        
    else:
        
        print('Sua matriz é de Markov.')

Sua matriz é de Markov.


### Equacionando o problema:

$$\begin{cases}g_1 = 0.9 \cdot g_0 + 0.2 \cdot a_0 \\ a_1 = 0.1 \cdot g_0 + 0.8 \cdot a_0\end{cases}$$

Essas equações descrevem o movimento de consumidores entre ambientes. Temos aí equações que conectam o estado inicial ao estado em $t = 1$, mas tanto faz; poderíamos considerar uma equação em $t-1$ e $t$. Note que o sistema é idêntico a:

$$\begin{bmatrix}g_1\\a_1\end{bmatrix} = \begin{bmatrix}0.9 & 0.2 \\ 0.1 & 0.8\end{bmatrix}\begin{bmatrix}g_0\\a_0\end{bmatrix}$$

Isto resolve o subitem 1. Vamos para o subitem 2. Precisamos diagonalizar $A$.

In [19]:
#Crio o espectro (cjto. de autovalores) e a matriz espectral (colunas = autovetores) unitária.

spectre, S = np.linalg.eig(A)

In [20]:
#Lembro que a matriz Lambda de autovalores é diagonal com autovalores nas entradas.

Lambda = np.diag(spectre)

In [21]:
np.linalg.inv(S)

array([[-0.99491358,  0.11624965],
       [-0.05842064, -0.99997702]])

Então podemos escrever:

$$A = \begin{bmatrix} 0.894 & -0.707 \\ 0.447 & \phantom{-}0.707\end{bmatrix}\begin{bmatrix}1 & 0\\0 & 0.7\end{bmatrix}\begin{bmatrix}\phantom{-}0.745 & 0.745 \\ -0.471 & 0.943\end{bmatrix}$$

Ou, no caso do subitem 3,

$$A = \begin{bmatrix} 0.894 & -0.707 \\ 0.447 & \phantom{-}0.707\end{bmatrix}\begin{bmatrix}1^{k} & 0\\0 & 0.7^{k}\end{bmatrix}\begin{bmatrix}\phantom{-}0.745 & 0.745 \\ -0.471 & 0.943\end{bmatrix}$$

Tradicionalmente, pessoas faziam $k \to \infty$ na mão!!! Por sorte, hoje temos módulos numéricos que computam isso bem rápido, e nem precisamos do $\infty$.

In [22]:
#Subitem 4. Duopólio converge para 2/3 da população na Google e 1/3 na Apple:

np.linalg.matrix_power(A, 1000) @ np.array([100, 80]).T

array([ 6.29429800e-39, -3.67725383e-40])

### Problema 1 (d)

Não vou explicar aqui os prolegômenos do enunciado. Vamos simplesmente computar as soluções.

In [23]:
C = np.array([
    [0.4, 0.0, 0.1],
    [0.0, 0.1, 0.8],
    [0.5, 0.7, 0.1]
])

In [24]:
C_prime = np.array([
    [0, 2],
    [2, 0]
])

In [25]:
C_twice_prime = np.array([
    [0.5, 2.0],
    [0.0, 0.5]
])

In [26]:
for linear_economy in [C, C_prime, C_twice_prime]:
    
    if any (np.linalg.eig(linear_economy)[0] > 1):
        
        print('Sua economia não é estável.')
        
    else:
        
        print(f'Sua economia é estável e a inversa de I - C é dada por:\n {np.linalg.inv(np.eye(np.shape(linear_economy)[0]) - linear_economy)}')

Sua economia é estável e a inversa de I - C é dada por:
 [[2.38095238 0.66666667 0.85714286]
 [3.80952381 4.66666667 4.57142857]
 [4.28571429 4.         5.14285714]]
Sua economia não é estável.
Sua economia é estável e a inversa de I - C é dada por:
 [[2. 8.]
 [0. 2.]]


### Problema 2 (a)

Preciso que seja $\langle e, a \rangle = 0$, onde $e = b - p$ é o erro de aproximação. *Also*, sei que $p$ vai ser um múltiplo de $a$, digamos, $p = \hat{x}a$, onde $\hat{x}$ é um **escalar**. Nossa equação de interesse será a seguinte:

$$a^{T}(b - \hat{x}a) = 0,$$

e equivale a

$$a^{T}b - \hat{x}a^{T}a = 0,$$

ou seja:

$$\hat{x} = \frac{a^{T}b}{a^{T}a} \in \mathbb{R}.$$

Segue que:

$$p = \frac{a^{T}b}{a^{T}a}a.$$

Ok, vamos aplicar ao problema 1, só pra termos uma ideia.

In [27]:
x = np.array([-100, -100, -100, 400])
y = np.array([-200, -50, -50, 400])

In [28]:
#Proj de x sobre y:

((y @ x) / (y @ y)) * y

array([-185.36585366,  -46.34146341,  -46.34146341,  370.73170732])

### Problema 2 (b)

$$P = \frac{aa^{T}}{a^{T}a}$$

Evidentemente simétrica pois se $a$ é $k \times 1$, então $a^{T}$ é $1 \times k$, donde $aa^{T}$ é $k \times k$; daí, basta notar que cada entrada $x[i][j]$ da matriz $k \times k$ será da forma $a[i] \cdot a[j]$. Então $x[i][j] = a[i]\cdot a[j] = a[j] \cdot a[i] = x[j][i]$.

Pra mostrar que $P^{2} = P$, basta multiplicar $P$ por $P$. Não entramos em detalhes operacionais aqui.

### Problema 2 (c)

Deriva e iguala a zero. O mantra dos economistas na graduação.

$$\partial_{x}E = 2 [(2x - b_1) \cdot 2 + (3x - b_2) \cdot 3 + (4x - b_3) \cdot 4] = 0$$

Daí,

$$\hat{x} = \frac{2b_1 + 3b_2 + 4b_3}{2^{2} + 3^{2} + 4^{2}} = \frac{[2, 3, 4]^{T}b}{[2, 3, 4]^{T}[2, 3, 4]}$$

### Problema 2 (d)

De novo, não quero fazer as $n$ equações normais necessárias. É bastante óbvio no que vai dar:

$$\hat{x} = (A^{T}A)^{-1}A^{T}b$$

O termo com a inversa da matriz simétrica hermitiana $(A^{T}A)$ é a mesma coisa que $\frac{1}{a^{T}a}$, já que a operação de inverso multiplicativo no grupo das matrizes é da forma $M \mapsto M^{-1}$. O outro termo é idêntico.

### Problema 2 (e)

Temos que resolver equações como $1 = F + 50 \cdot n$, etc. No fundo, você quer resolver um sistema linear onde a sua matriz de coeficientes, $A$, tem como colunas um vetor de $1$'s e o vetor $\mathbf{n}$. O lado direito é simplesmente $\mathbf{c}$. Algo como:

$$\begin{bmatrix}\mathbf{1} & \mathbf{n}\end{bmatrix}\begin{bmatrix}F & \alpha\end{bmatrix} = \mathbf{c}$$

Bacana. Mas isso não vai dar certo. É resolver um sistema do tipo $Ax = b$ quando $x \not \in \mathcal{C}(A)$. Tem linhas demais. Então vamos usar uma solução de *least squares*:

$$\hat{x} = [\hat{F}, \hat{\alpha}] = (A^{T}A)^{-1}A^{T}\mathbf{c}$$

In [29]:
n = np.array([50, 48, 59, 56, 57, 56])

c = np.array([1, 1, 1.3, 1.5, 1.7, 1.6])

first_column = np.ones(np.shape(n)[0])

In [30]:
first_column

array([1., 1., 1., 1., 1., 1.])

In [31]:
A = np.vstack((first_column, n)).T

In [32]:
x_hat = np.linalg.inv(A.T @ A) @ A.T @ c

Melhor aproximação linear do custo por segundo dos leilões de posição:

In [33]:
print(f'c = {x_hat[0]} + {x_hat[1]}n')

c = -1.6189285714285075 + 0.05464285714285677n
