### Monitoria: dicas para a terceira prova.

Hoje eu quero passar algumas dicas para a prova e um pouquinho de otimização (se houver tempo hábil).

In [1]:
#Acredito que estes dois bastam.

import numpy as np

import pandas as pd

### Exercício 1

In [5]:
#Um pouco de housekeeping:

path = 'https://ftp.ibge.gov.br/Contas_Nacionais/Matriz_de_Insumo_Produto/2015/Matriz_de_Insumo_Produto_2015_Nivel_20.xls'

mip = pd.read_excel(path,
                 sheet_name=-2,
                 skipfooter=3,
                 skiprows=4)

mip = mip.drop(['Unnamed: 0', 'Unnamed: 1'], 1)

mip.columns = mip.index

mip

0         1         2         3         4         5         6   \
0   0.040534  0.000516  0.076445  0.000242  0.001362  0.002558  0.009141   
1   0.001104  0.054427  0.042094  0.016943  0.006557  0.011194  0.000205   
2   0.206465  0.111786  0.273618  0.075310  0.081036  0.205439  0.057913   
3   0.023441  0.009710  0.012187  0.331112  0.039685  0.000750  0.014077   
4   0.000011  0.001154  0.003275  0.000300  0.013902  0.000412  0.003523   
5   0.000593  0.012595  0.000921  0.000045  0.065599  0.093546  0.001069   
6   0.059393  0.031024  0.078769  0.018258  0.027748  0.057656  0.027429   
7   0.020042  0.084843  0.049972  0.021767  0.008131  0.012167  0.050983   
8   0.000033  0.001502  0.001043  0.001548  0.000233  0.001131  0.002261   
9   0.000207  0.004003  0.005706  0.006637  0.006463  0.002284  0.013183   
10  0.015250  0.022172  0.017518  0.022554  0.017945  0.014267  0.023550   
11  0.000036  0.001358  0.001831  0.004371  0.003976  0.001681  0.033814   
12  0.002276  0.054102  0.030419  0.028781  0.021883  0.013420  0.038377   
13  0.000723  0.027511  0.009141  0.014263  0.024540  0.006942  0.031867   
14  0.000632  0.005398  0.003373  0.003216  0.002457  0.001320  0.003998   
15  0.000144  0.003802  0.001945  0.002158  0.001292  0.000781  0.002936   
16  0.000012  0.000284  0.000161  0.000155  0.000119  0.000072  0.000236   
17  0.000020  0.000383  0.000221  0.000206  0.000158  0.000100  0.000296   
18  0.000350  0.002930  0.001225  0.002736  0.000027  0.000278  0.002877   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9         10        11        12        13  \
0   0.000564  0.021891  0.000228  0.000056  0.000054  0.000158  0.000623   
1   0.000288  0.000323  0.000296  0.000093  0.000630  0.000319  0.000202   
2   0.182664  0.224327  0.028201  0.010146  0.009364  0.030847  0.042497   
3   0.003913  0.009492  0.006676  0.003280  0.000634  0.003503  0.017968   
4   0.001808  0.005387  0.000596  0.000845  0.000615  0.001556  0.013083   
5   0.003175  0.002585  0.016449  0.003031  0.002923  0.002924  0.009330   
6   0.047033  0.064995  0.025365  0.005884  0.003245  0.020377  0.018940   
7   0.112695  0.018858  0.009927  0.014781  0.000942  0.014391  0.009336   
8   0.002417  0.001001  0.003273  0.005981  0.000168  0.004922  0.004399   
9   0.007661  0.003987  0.120991  0.039338  0.001430  0.129362  0.009093   
10  0.024751  0.013419  0.029391  0.124014  0.037899  0.017270  0.021851   
11  0.006732  0.019863  0.012231  0.009615  0.002742  0.016508  0.010985   
12  0.018693  0.007623  0.042332  0.041392  0.004571  0.071075  0.023356   
13  0.029922  0.013462  0.069697  0.044027  0.002503  0.018805  0.026294   
14  0.003181  0.001265  0.004337  0.003800  0.000432  0.006485  0.002594   
15  0.003629  0.000466  0.002657  0.005666  0.000265  0.013922  0.006718   
16  0.000105  0.000061  0.000235  0.000227  0.000027  0.000389  0.000134   
17  0.000139  0.000133  0.007882  0.000298  0.000034  0.000695  0.000240   
18  0.003137  0.001192  0.015157  0.003844  0.000230  0.002666  0.004101   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          14        15        16        17        18  19  
0   0.001404  0.001574  0.001661  0.000183  0.001783   0  
1   0.000338  0.000134  0.000212  0.000239  0.000127   0  
2   0.018688  0.021899  0.064071  0.044225  0.048900   0  
3   0.007396  0.008164  0.006072  0.020790  0.017009   0  
4   0.013227  0.003446  0.008179  0.002650  0.010801   0  
5   0.017093  0.003645  0.008498  0.003416  0.002480   0  
6   0.008344  0.013360  0.046589  0.016478  0.023133   0  
7   0.011789  0.014493  0.008904  0.009474  0.071325   0  
8   0.015034  0.005290  0.019075  0.003415  0.076306   0  
9   0.019233  0.016647  0.009094  0.012008  0.017804   0  
10  0.072897  0.006419  0.011863  0.022024  0.016191   0  
11  0.004581  0.010621  0.005402  0.103735  0.017783   0  
12  0.014335  0.014308  0.010975  0.065323  0.026

Não posso soprar a resposta, mas posso dizer o que vocês irão usar.

In [4]:
#Dado um array

A = np.array([
    [0.4, 0.3, 0.3],
    [0.1, 0.9, 0.0],
    [0.2, 0.6, 0.2]
])

#Como invertê-lo?

print(np.linalg.inv(A))

#Como recuperar o seu shape?

print(A.shape)

#Como multiplicá-lo por ele mesmo? (ou por outro array)

print(A @ A)

[[ 6.          4.         -9.        ]
 [-0.66666667  0.66666667  1.        ]
 [-4.         -6.         11.        ]]
(3, 3)
[[0.25 0.57 0.18]
 [0.13 0.84 0.03]
 [0.18 0.72 0.1 ]]


In [9]:
#Dado um inteiro positivo

n = 3

#Como criar uma matriz identidade n por n?

print(np.eye(n))

#Como criar uma matriz de zeros n por n?

print(np.zeros(n))

I = np.eye(n)

#Como forçar uma certa entrada a ter um certo valor?

I[1, 2] = 2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0. 0. 0.]


array([[1., 0., 0.],
       [0., 1., 2.],
       [0., 0., 1.]])

### Questão 2

Se $A$ é uma matriz cujas colunas são os vetores $a_1, ..., a_n$, então a matriz que toma projeta um vetor qualquer sobre o espaço coluna de $A$ é

$$P = A(A^TA)^{-1}A^T$$

In [11]:
#Já vimos como inverter. Como transpor A?

A_transpose = A.T

A_transpose

#Agora basta aplicarmos a matriz P a um vetor qualquer.

y = np.array([
    [1],
    [2],
    [3]
])

A_transpose @ y

array([[1.2],
       [3.9],
       [0.9]])

Não vou dar a dica pro $\widehat{\beta}$ porque todo estudante de economia está careca de saber. Pra distância euclideana, basta lembrarmos que toda norma induz uma métrica de forma bastante natural, bastando pôrmos

$$d(x, y) = \left\lVert x - y \right\rVert$$

para quaisquer dois pontos $x, y$ do espaço normado subjacente.

Finalmente, como podemos testar se um conjunto de vetores é LI? Múltiplas formas. Basta computar o determinante de $A$ para ver se as colunas formam um conjunto LI, por exemplo.

### Questão 3

Vou ser generoso e montar a matriz:

$$P = \begin{bmatrix} 0.8 & 0.0 & 0.2 \\ 0.0 & 0.7 & 0.3 \\ 0.1 & 0.4 & 0.5 \end{bmatrix}$$

In [2]:
P = np.array([
    [0.8, 0.0, 0.2],
    [0.0, 0.7, 0.3],
    [0.1, 0.4, 0.5]
])

In [10]:
s0 = [0.8, 0.1, 0.1]

In [6]:
s0 @ P

array([0.18, 0.5 , 0.32])

In [7]:
P.T @ s0

array([0.18, 0.5 , 0.32])

Você precisa de algumas informações para resolver o exercício.

In [13]:
#Se quiser fazer do jeito raiz:

#Como computar o espectro de uma matriz?
#Como computar a matriz de autovetores associada aos elementos do espectro?

spectre = np.linalg.eig(A)[0]

S = np.linalg.eig(A)[1]

$A = S\Lambda S^{-1}$

In [16]:
#Se quiser fazer do jeito Nutella:

#Como computar uma potência k qualquer de uma matriz?

Ak = np.linalg.matrix_power(A, 4)

In [17]:
Ak @ s0

array([[0.169 , 0.7509, 0.0801],
       [0.1471, 0.8013, 0.0516],
       [0.1566, 0.7794, 0.064 ]])

### Questão 4

Como padronizar dados?

In [20]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#Subtraindo média:

X_c = X - np.mean(X, axis=0)

print(X_c)

#Dividindo cada elemento pelo DP:

X_s = X_c / np.sqrt(np.var(X_c))

print(X_s)

[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
