# Monitoria $n > 5$

## Tópico 1: A Lei dos Cossenos

**Definição.** Dados dois vetores $\mathbf{x}$ e $\mathbf{y}$ em $\mathbb{R}^{n}$, o produto interno usual entre eles é definido como sendo:

$$\langle \mathbf{x}, \mathbf{y} \rangle \equiv ||x|| \cdot ||y|| \cdot \cos(\theta),$$

onde $\theta$ é o ângulo entre $\mathbf{x}$ e $\mathbf{y}$.

$\langle \mathbf{x}, \mathbf{y} \rangle = \sum_{i}^{n} x_i \cdot y_i$

Uma forma de definir **norma** de um vetor $\mathbf{x}$ qualquer é usando o produto interno para induzí-la:

$$||\mathbf{x}|| \equiv \sqrt{\langle x, x \rangle}.$$

Uma norma induz uma **métrica**, bastando pôrmos: $d(x, y) \equiv ||x - y||$.

**Teorema.** Dados dois vetores $\mathbf{a}$ e $\mathbf{b}$, ambos diferentes do vetor nulo, temos:

$$||\mathbf{a} - \mathbf{b}||^{2} = ||\mathbf{a}||^{2} + ||\mathbf{b}||^{2} - 2 \cdot ||\mathbf{a}|| \cdot ||\mathbf{b}|| \cdot \cos(\theta)$$

**Demonstração.** Basta notarmos que:

$$||\mathbf{a} - \mathbf{b}||^{2} = \langle \mathbf{a} - \mathbf{b}, \mathbf{a} - \mathbf{b} \rangle = (\star)$$

Agora, lembro que o produto interno usual é uma forma sesquilinear. Daí, obtemos:

$$(\star) = \langle \mathbf{a}, \mathbf{a} \rangle - 2 \cdot \langle \mathbf{a}, \mathbf{b} \rangle + \langle \mathbf{b}, \mathbf{b} \rangle = ||\mathbf{a}||^{2} - 2 \cdot ||\mathbf{a}|| \cdot ||\mathbf{b}|| \cdot \cos(\theta) + ||\mathbf{b}||^{2},$$

que é justamente o que queríamos demonstrar.

## Tópico 2: Eliminação Gaussiana

Metade das aplicações de álgebra linear pode ser entendida a partir do algoritmo de eliminação. Vamos aprender como funciona esse algoritmo a partir de um exemplo concreto. Ponhamos:

$$
A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9\\
\end{bmatrix}
$$

Vamos escalonar esta matriz usando o Python.

In [1]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
A[1]

array([4, 5, 6])

In [3]:
#Primeiro passo: produzir zeros debaixo do primeiro pivô (pivô de ordem k é o primeiro elemento não-nulo da linha k)

A[1] = A[1] - 4 * A[0]
A[2] = A[2] - 7 * A[0]

print(A)

[[  1   2   3]
 [  0  -3  -6]
 [  0  -6 -12]]


In [4]:
#Segundo passo: produzir zeros debaixo do segundo pivo:

A[2] = A[2] - 2 * A[1]

print(A)

[[ 1  2  3]
 [ 0 -3 -6]
 [ 0  0  0]]


In [5]:
#Se quiséssemos forma escalonada reduzida por linha (rref no matlab, row reduced echelon form)...

#Terceiro passo (opcional):

A[1] = A[1] / -3

print(A)

[[1 2 3]
 [0 1 2]
 [0 0 0]]


In [6]:
#Quarto e último passo: produzir zero em cima do pivo de ordem 2:

A[0] = A[0] - 2 * A[1]

print(A)

[[ 1  0 -1]
 [ 0  1  2]
 [ 0  0  0]]


$$\begin{bmatrix}
1 & 0 & 1\\
0 & 5 & 0\\
0 & 0 & 3\\
\end{bmatrix}
$$

Lower triangular (L)

In [7]:
np.linalg.inv(A)

LinAlgError: Singular matrix

**Condition Number**:

$$\kappa = \frac{|\lambda_{\text{max}|}}{|\lambda_{\text{min}}|}$$

$$\det(A) = \prod_i \lambda_i$$

# Problema 1 (a)

In [8]:
x = np.array([-100, -100, -100, 400])
y = np.array([-200, -50, -50, 400])

In [9]:
a = [-100, -100, -100, 400]
b = [-200, -50, -50, 400]

a + b

[-100, -100, -100, 400, -200, -50, -50, 400]

In [10]:
x + y

array([-300, -150, -150,  800])

In [11]:
x @ y #nao sao ortogonais pq produto interno deu um numero positivo

190000

In [12]:
np.dot(x, y)

190000

In [14]:
np.linalg.norm(x)

435.88989435406734

In [15]:
np.linalg.norm(y)

452.76925690687085

In [16]:
np.linalg.norm(x-y, ord=1)

200.0

In [17]:
np.linalg.norm(x-y)

122.47448713915891

In [18]:
z = np.vstack((x, y))

print(z)

[[-100 -100 -100  400]
 [-200  -50  -50  400]]


In [20]:
ztranspose = z.T

POSTO (RANK) de uma matriz é simplesmente o numero de colunas LI ou o número de linhas não-nulas depois do algoritmo de eliminação gaussiana.

In [22]:
np.linalg.matrix_rank(ztranspose)

2

# Problema 1 (b)

In [23]:
A = np.array([
    [0.9, 0.2],
    [0.1, 0.8]
])

In [24]:
A.transpose()

array([[0.9, 0.1],
       [0.2, 0.8]])

In [25]:
A.T

array([[0.9, 0.1],
       [0.2, 0.8]])

In [26]:
A.T @ A

array([[0.82, 0.26],
       [0.26, 0.68]])

In [27]:
np.linalg.inv(A)

array([[ 1.14285714, -0.28571429],
       [-0.14285714,  1.28571429]])

In [28]:
np.linalg.matrix_rank(A)

2

In [30]:
np.trace(A)

1.7000000000000002

In [31]:
np.linalg.det(A)

0.7000000000000001

$p(\lambda) = \lambda^{2} - \lambda \cdot \text{tr}(A) + \det(A)$

In [32]:
w, v = np.linalg.eig(A)

In [33]:
w

array([1. , 0.7])

Cenas dos próximos capítulos:

Autovetores e autovalres se

$Av = \lambda v$

Se $\lambda = 1$, efetivamente tenho pto fixo do operador $A$

$Av = v$